---
- hosts: all
  become: true
  tasks:
    - name: Install Apache2 package
      apt:
        name: apache2
        state: latest

    - name: update repository index 
      apt: 
        update_cache: yes

    - name: Add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest

