---
- hosts: all
  become: true
  tasks:
    - name: Install Apache and php in Ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"   

        
    - name: Install Apache and php in Centos
      yum:
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"    
