---
- hosts: all
  become: true
  pre_tasks:
    
    - name: install updates (centos)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"


    - name: install updates (ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
    - name: create simone user
      tags: always
      user:
        name: simone
        groups: root



- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src:  https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 755
        owner: root
        group: root


- hosts: webservers
  become: yes
  tasks:

    - name: Install Apache and php in Ubuntu
      tags: apache,apache2,ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"   

        
    - name: Install Apache and php in Centos
      tags: apache,httpd,centos
      dnf:
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"  

    - name: start httpd (Centos)
      tags: apache,centos,httpd
      service:
        name: httpd
        enabled: yes
        state: started
      when: ansible_distribution == "CentOS" 

    - name: change e-mail addrress for admin
      tags: apache,centos,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin chiieche29@gmail.com
      when: ansible_distribution == "CentOS" 
      register: httpd

    - name: restart httpd (Centos)
      tags: apache,httpd,centos
      service:
        name: httpd
        state: restarted
      when: httpd.changed


    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 644


- hosts: dbservers
  become: true
  tasks:
    
    - name: install maraidb packge(centos)
      tags: mariadb,db,centos
      dnf: 
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS" 

    - name: install maraidb packge(ubuntu)
      tags: mariadb,db,ubuntu
      apt: 
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: fileservers
  become: true
  tasks:

    - name: install samba package  
      tags: samba
      package:
        name: samba
        state: latest
