
- name: install maraidb package(centos)
  tags: mariadb,db,centos
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install maraidb packge(ubuntu)
  tags: mariadb,db,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

